### ISSUE TITLE
This package changes global package-user-dir?

### ISSUE THREAD

**Issue by conao3** [emacs-elsa/flycheck-elsa#8] opened 2019-11-12 09:10 UTC
Hi!

I noticed my `package.el` attempt to install develop package local `.cask` directory after this package installed.

**Comment by conao3** [comment] 2019-11-13 04:27
`flycheck-elsa--enable-p` cause this issue.
```
package-user-dir
;;=> "~/.emacs.d/local/26.3/elpa"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

Switch flycheck-elsa.el and then `M-: (flycheck-elsa--enable-p)`

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

package-user-dir
;;=> "/home/conao/dev/forks/flycheck-elsa/.cask/26.3/elpa"
```

**Comment by Fuco1** [comment] 2019-11-13 17:39
This is how cask works.  It installs packages to a separate local directory.

**Comment by Fuco1** [comment] 2019-11-13 17:43
Ok I understand now what the problem is.  Cask runs some side-effects to setup the paths.  That should be fixed on the cask side I guess.  I'll review your patch to see how it works.

**Comment by conao3** [comment] 2019-11-13 17:44
Good, thanks!

**Closed as completed** 2020-01-04 15:23 UTC
